-- Keep historical appointments, but allow a cancelled/completed slot to be booked again.
-- Only new and confirmed appointments must be unique per doctor/date/time.

begin;

-- Names used by the previous Dream Smile schema and by PostgreSQL's default
-- naming convention. The first one is the constraint currently present in the
-- connected project.
alter table public.appointments
  drop constraint if exists appointments_doctor_slot_unique;
alter table public.appointments
  drop constraint if exists appointments_doctor_id_appointment_date_appointment_time_key;

drop index if exists public.appointments_doctor_slot_unique;    
drop index if exists public.appointments_doctor_id_appointment_date_appointment_time_key;

do $migration$
declare
  object_name text;
begin
  -- Drop any global UNIQUE constraint on exactly these three slot columns,
  -- regardless of the name generated by an earlier schema version.
  for object_name in
    select constraint_row.conname
    from pg_constraint as constraint_row
    where constraint_row.conrelid = 'public.appointments'::regclass
      and constraint_row.contype = 'u'
      and array_length(constraint_row.conkey, 1) = 3
      and (
        select array_agg(attribute_row.attname order by attribute_row.attname)
        from unnest(constraint_row.conkey) as key_row(attnum)
        join pg_attribute as attribute_row
          on attribute_row.attrelid = constraint_row.conrelid
         and attribute_row.attnum = key_row.attnum
      ) = array['appointment_date', 'appointment_time', 'doctor_id']::name[]
  loop
    execute format('alter table public.appointments drop constraint %I', object_name);
  end loop;

  -- Drop an equivalent standalone global UNIQUE index, if an earlier migration
  -- created one without attaching it as a table constraint.
  for object_name in
    select index_class.relname
    from pg_index as index_row
    join pg_class as index_class on index_class.oid = index_row.indexrelid
    where index_row.indrelid = 'public.appointments'::regclass
      and index_row.indisunique
      and index_row.indpred is null
      and index_row.indexprs is null
      and index_row.indnkeyatts = 3
      and (
        select array_agg(attribute_row.attname order by attribute_row.attname)
        from unnest(index_row.indkey) as key_row(attnum)
        join pg_attribute as attribute_row
          on attribute_row.attrelid = index_row.indrelid
         and attribute_row.attnum = key_row.attnum
      ) = array['appointment_date', 'appointment_time', 'doctor_id']::name[]
  loop
    execute format('drop index if exists public.%I', object_name);
  end loop;
end
$migration$;

-- Recreate the expected partial index even if an index with this name had an
-- outdated definition.
drop index if exists public.appointments_active_doctor_slot_unique;

create unique index appointments_active_doctor_slot_unique
  on public.appointments (doctor_id, appointment_date, appointment_time)
  where status in ('new', 'confirmed');

commit;
