export type AppointmentStatus = "new" | "confirmed" | "completed" | "cancelled";
export type Database = { public: { Tables: {
  services: { Row:{id:string;name:string;duration_minutes:number|null;active:boolean;created_at:string}; Insert:{id?:string;name:string;duration_minutes?:number|null;active?:boolean;created_at?:string}; Update:{name?:string;duration_minutes?:number|null;active?:boolean}; Relationships:[] };
  doctors: { Row:{id:string;name:string|null;specialty:string;phone:string|null;active:boolean;created_at:string}; Insert:{id?:string;name?:string|null;specialty:string;phone?:string|null;active?:boolean;created_at?:string}; Update:{name?:string|null;specialty?:string;phone?:string|null;active?:boolean}; Relationships:[] };
  doctor_accounts: { Row:{id:string;user_id:string;doctor_id:string;created_at:string}; Insert:{id?:string;user_id:string;doctor_id:string;created_at?:string}; Update:{user_id?:string;doctor_id?:string}; Relationships:[] };
  availability: { Row:{id:string;doctor_id:string;date:string;start_time:string;end_time:string;available:boolean}; Insert:{id?:string;doctor_id:string;date:string;start_time:string;end_time:string;available?:boolean}; Update:{start_time?:string;end_time?:string;available?:boolean}; Relationships:[] };
  appointments: { Row:{id:string;patient_name:string;patient_phone:string;comment:string|null;service_id:string;doctor_id:string;appointment_date:string;appointment_time:string;status:AppointmentStatus;created_at:string}; Insert:{id?:string;patient_name:string;patient_phone:string;comment?:string|null;service_id:string;doctor_id:string;appointment_date:string;appointment_time:string;status?:AppointmentStatus;created_at?:string}; Update:{service_id?:string;doctor_id?:string;appointment_date?:string;appointment_time?:string;status?:AppointmentStatus}; Relationships:[] };
  notification_jobs: { Row:{id:string;appointment_id:string;recipient_type:"patient"|"doctor";recipient_phone:string;event_type:"booking_created"|"booking_confirmed"|"booking_rescheduled"|"booking_cancelled"|"appointment_reminder";scheduled_for:string;status:"pending"|"processing"|"sent"|"failed";attempts:number;last_error:string|null;sent_at:string|null;created_at:string;dedupe_key:string;payload:Record<string,unknown>;locked_at:string|null;provider_message_id:string|null}; Insert:{id?:string;appointment_id:string;recipient_type:"patient"|"doctor";recipient_phone:string;event_type:"booking_created"|"booking_confirmed"|"booking_rescheduled"|"booking_cancelled"|"appointment_reminder";scheduled_for?:string;status?:"pending"|"processing"|"sent"|"failed";attempts?:number;last_error?:string|null;sent_at?:string|null;created_at?:string;dedupe_key:string;payload?:Record<string,unknown>;locked_at?:string|null;provider_message_id?:string|null}; Update:{scheduled_for?:string;status?:"pending"|"processing"|"sent"|"failed";attempts?:number;last_error?:string|null;sent_at?:string|null;locked_at?:string|null;provider_message_id?:string|null}; Relationships:[] };
  doctor_schedules: { Row:{id:string;doctor_id:string;weekday:number;start_time:string|null;end_time:string|null;break_start:string|null;break_end:string|null;active:boolean;created_at:string;updated_at:string}; Insert:{id?:string;doctor_id:string;weekday:number;start_time?:string|null;end_time?:string|null;break_start?:string|null;break_end?:string|null;active?:boolean;created_at?:string;updated_at?:string}; Update:{start_time?:string|null;end_time?:string|null;break_start?:string|null;break_end?:string|null;active?:boolean;updated_at?:string}; Relationships:[] };
  schedule_exceptions: { Row:{id:string;doctor_id:string;date:string;type:"day_off"|"custom_hours";start_time:string|null;end_time:string|null;break_start:string|null;break_end:string|null;created_at:string;updated_at:string}; Insert:{id?:string;doctor_id:string;date:string;type:"day_off"|"custom_hours";start_time?:string|null;end_time?:string|null;break_start?:string|null;break_end?:string|null;created_at?:string;updated_at?:string}; Update:{type?:"day_off"|"custom_hours";start_time?:string|null;end_time?:string|null;break_start?:string|null;break_end?:string|null;updated_at?:string}; Relationships:[] };
}; Views:Record<string,never>; Functions:{
  get_occupied_appointment_slots:{Args:{p_doctor_ids:string[];p_from:string;p_to:string};Returns:{doctor_id:string;appointment_date:string;appointment_time:string}[]};
  create_public_appointment:{Args:{p_service_id:string;p_doctor_id:string;p_date:string;p_time:string;p_patient_name:string;p_patient_phone:string;p_comment:string|null};Returns:string};
  get_blocking_appointments:{Args:{p_doctor_ids:string[];p_from:string;p_to:string};Returns:{doctor_id:string;appointment_date:string;appointment_time:string;duration_minutes:number}[]};
  create_admin_appointment:{Args:{p_service_id:string;p_doctor_id:string;p_date:string;p_time:string;p_patient_name:string;p_patient_phone:string;p_comment:string|null};Returns:string};
  reschedule_admin_appointment:{Args:{p_appointment_id:string;p_doctor_id:string;p_date:string;p_time:string};Returns:string};
  complete_doctor_appointment:{Args:{p_appointment_id:string};Returns:string};
  claim_notification_jobs:{Args:{p_limit?:number};Returns:Database["public"]["Tables"]["notification_jobs"]["Row"][]};
}; Enums:Record<string,never>; CompositeTypes:Record<string,never> } };
