"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import type { BookingSlot, Doctor, Service } from "@/types";
import { Arrow, CalendarIcon } from "./icons";

const labels=["Услуга","Специалист","Дата","Время"];
function getDates(){const dates:Date[]=[];const now=new Date();now.setHours(0,0,0,0);for(let i=0;i<14;i++){const date=new Date(now);date.setDate(now.getDate()+i);dates.push(date)}return dates}
function isoDate(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}

export function Booking(){
  const[services,setServices]=useState<Service[]>([]);const[doctors,setDoctors]=useState<Doctor[]>([]);const[connected,setConnected]=useState<boolean|null>(null);
  const[step,setStep]=useState(0);const[serviceId,setServiceId]=useState("");const[doctorChoice,setDoctorChoice]=useState("any");const[assignedDoctorId,setAssignedDoctorId]=useState("");const[date,setDate]=useState("");const[time,setTime]=useState("");const[slots,setSlots]=useState<BookingSlot[]>([]);const[message,setMessage]=useState("");const[loading,setLoading]=useState(false);
  const dates=useMemo(()=>getDates(),[]);const selectedService=services.find(item=>item.id===serviceId)?.name;const selectedDoctor=doctorChoice==="any"?"Любой специалист":doctors.find(item=>item.id===doctorChoice)?.specialty;

  useEffect(()=>{let active=true;fetch("/api/catalog").then(async response=>{const body=await response.json();if(!active)return;if(!response.ok){setConnected(false);setMessage(body.error||"Система записи пока не подключена.");return}setServices(body.services);setDoctors(body.doctors);setConnected(true)}).catch(()=>{if(active){setConnected(false);setMessage("Система записи пока не подключена.")}});return()=>{active=false}},[]);

  async function chooseDate(value:string){setDate(value);setTime("");setMessage("");setStep(3);setLoading(true);const params=new URLSearchParams({serviceId,date:value});if(doctorChoice!=="any")params.set("doctorId",doctorChoice);try{const response=await fetch(`/api/availability?${params}`);const body=await response.json();if(!response.ok){setSlots([]);setMessage(body.error||"Не удалось загрузить свободное время.")}else setSlots(body.slots)}catch{setSlots([]);setMessage("Не удалось загрузить свободное время.")}finally{setLoading(false)}}
  function chooseTime(slot:BookingSlot){setTime(slot.time);setAssignedDoctorId(slot.doctorId);setMessage("")}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setMessage("");const data=new FormData(event.currentTarget);try{const response=await fetch("/api/appointments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({serviceId,doctorId:assignedDoctorId,date,time,patientName:String(data.get("name")),phone:String(data.get("phone")),comment:String(data.get("comment")||"")})});const body=await response.json();if(response.status===409){setTime("");await chooseDate(date);setMessage("Это время уже занято. Выберите другое.")}else setMessage(body.message||body.error)}catch{setMessage("Не удалось создать заявку. Попробуйте позже.")}finally{setLoading(false)}}

  return <section id="booking" className="section-pad bg-white"><div className="container-page"><div className="grid gap-7 lg:grid-cols-[.7fr_1.3fr] lg:gap-16"><div><p className="eyebrow">Онлайн-запись</p><h2 className="section-title mt-4">Выберите удобное время</h2><p className="mt-6 max-w-md text-sm leading-7 text-muted">Пройдите четыре коротких шага. Заявка будет отправлена в клинику и потребует подтверждения.</p><div className="mt-9 space-y-3 text-sm"><p><span className="text-muted">Услуга:</span> <b>{selectedService||"не выбрана"}</b></p><p><span className="text-muted">Специалист:</span> <b>{selectedDoctor||"не выбран"}</b></p><p><span className="text-muted">Дата и время:</span> <b>{date?new Date(`${date}T00:00:00`).toLocaleDateString("ru-RU"):"—"}{time?`, ${time}`:""}</b></p></div></div><div className="rounded-[28px] border border-line bg-background p-4 sm:p-7 lg:p-9"><ol aria-label="Шаги записи" className="grid grid-cols-4 gap-2 border-b border-line pb-6">{labels.map((label,index)=><li key={label} className={index<=step?"text-primary":"text-muted"}><span className={`grid h-8 w-8 place-items-center rounded-full text-xs font-extrabold ${index<=step?"bg-primary text-white":"bg-white"}`}>{index+1}</span><span className="mt-2 hidden text-[11px] font-bold sm:block">{label}</span></li>)}</ol>
        <div className="min-h-[350px] pt-7">
          {connected===null&&<Notice>Подключаем систему записи…</Notice>}
          {connected===false&&<Notice>{message||"Система записи пока не подключена."}</Notice>}
          {connected&&step===0&&<Choice title="Выберите услугу">{services.map(item=><button key={item.id} onClick={()=>{setServiceId(item.id);setStep(1)}} className="focus-ring flex min-h-14 w-full items-center justify-between rounded-xl border border-line bg-white px-4 text-left text-sm font-bold transition hover:border-primary"><span>{item.name}</span><Arrow/></button>)}{!services.length&&<Notice>Активные услуги пока не добавлены.</Notice>}</Choice>}
          {connected&&step===1&&<Choice title="Выберите специалиста"><button onClick={()=>{setDoctorChoice("any");setStep(2)}} className="focus-ring flex min-h-14 w-full items-center justify-between rounded-xl border border-line bg-white px-4 text-left text-sm font-bold transition hover:border-primary"><span>Любой специалист</span><Arrow/></button>{doctors.map(item=><button key={item.id} onClick={()=>{setDoctorChoice(item.id);setStep(2)}} className="focus-ring flex min-h-14 w-full items-center justify-between rounded-xl border border-line bg-white px-4 text-left text-sm font-bold transition hover:border-primary"><span>{item.specialty}</span><Arrow/></button>)}</Choice>}
          {connected&&step===2&&<div><h3 className="text-xl font-bold">Выберите дату</h3><p className="mt-2 text-sm text-muted">Доступны ближайшие 14 дней</p><div className="mt-6 grid grid-cols-3 gap-2 sm:grid-cols-5 md:grid-cols-7">{dates.map(item=>{const value=isoDate(item);return <button key={value} onClick={()=>chooseDate(value)} className="focus-ring min-h-[72px] rounded-xl border border-line bg-white p-2 text-center transition hover:border-primary"><span className="block text-[10px] font-bold uppercase text-muted">{item.toLocaleDateString("ru-RU",{weekday:"short"})}</span><b className="mt-1 block text-lg">{item.getDate()}</b></button>})}</div></div>}
          {connected&&step===3&&!time&&<div><h3 className="text-xl font-bold">Выберите время</h3>{loading?<Notice>Проверяем свободные слоты…</Notice>:slots.length?<div className="mt-6 grid grid-cols-3 gap-2 sm:grid-cols-4">{slots.map(slot=><button key={`${slot.doctorId}-${slot.time}`} onClick={()=>chooseTime(slot)} className="focus-ring min-h-12 rounded-xl border border-line bg-white text-sm font-bold transition hover:border-primary hover:text-primary">{slot.time}</button>)}</div>:<Notice>{message||"На эту дату свободных слотов нет."}</Notice>}</div>}
          {connected&&step===3&&time&&<form onSubmit={submit}><div className="mb-5 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-secondary text-primary"><CalendarIcon/></span><div><h3 className="font-bold">Контактные данные</h3><p className="text-xs text-muted">{date} · {time}</p></div></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Имя" name="name" placeholder="Ваше имя" required/><Field label="Телефон" name="phone" type="tel" placeholder="Ваш телефон" required pattern="[+0-9 ()-]{7,}"/><label className="sm:col-span-2"><span className="mb-2 block text-xs font-bold">Комментарий</span><textarea name="comment" rows={3} placeholder="Необязательно" className="focus-ring w-full resize-none rounded-xl border border-line bg-white px-4 py-3 text-sm outline-none"/></label></div><button disabled={loading} className="btn-primary focus-ring mt-5 disabled:opacity-60">{loading?"Отправляем…":"Создать заявку"}<Arrow/></button>{message&&<p role="status" className="mt-4 rounded-xl bg-secondary p-4 text-sm font-bold leading-6 text-primary-dark">{message}</p>}<button type="button" onClick={()=>{setTime("");setMessage("")}} className="focus-ring mt-4 block text-sm font-bold text-muted hover:text-primary">← Изменить время</button></form>}
        </div>{connected&&step>0&&!(step===3&&time)&&<button onClick={()=>{setStep(step-1);setMessage("");if(step===3){setDate("");setSlots([])}}} className="focus-ring mt-4 text-sm font-bold text-muted hover:text-primary">← Назад</button>}</div></div></div></section>
}
function Notice({children}:{children:React.ReactNode}){return <p role="status" className="mt-5 rounded-xl border border-line bg-white p-4 text-sm font-bold leading-6 text-muted">{children}</p>}
function Choice({title,children}:{title:string;children:React.ReactNode}){return <div><h3 className="text-xl font-bold">{title}</h3><div className="mt-5 grid gap-2 sm:grid-cols-2">{children}</div></div>}
function Field({label,name,type="text",placeholder,required,pattern}:{label:string;name:string;type?:string;placeholder:string;required?:boolean;pattern?:string}){return <label><span className="mb-2 block text-xs font-bold">{label}</span><input name={name} type={type} placeholder={placeholder} required={required} pattern={pattern} className="focus-ring h-12 w-full rounded-xl border border-line bg-white px-4 text-sm outline-none"/></label>}
