"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { Appointment, Doctor, Service } from "@/types";
import type { AppointmentStatus } from "@/types/database";

type Screen="appointments"|"calendar"|"services"|"doctors";
const tabs:[Screen,string][]=[["appointments","Записи"],["calendar","Календарь"],["services","Услуги"],["doctors","Специалисты"]];
const statusLabels:Record<AppointmentStatus,string>={new:"Новая",confirmed:"Подтверждена",completed:"Завершена",cancelled:"Отменена"};
function localDate(offset=0){const date=new Date();date.setDate(date.getDate()+offset);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}

export function AdminDashboard(){
  const[screen,setScreen]=useState<Screen>("appointments");const[connected,setConnected]=useState<boolean|null>(null);const[error,setError]=useState("");
  const[appointments,setAppointments]=useState<Appointment[]>([]);const[services,setServices]=useState<Service[]>([]);const[doctors,setDoctors]=useState<Doctor[]>([]);const[filter,setFilter]=useState<"today"|"tomorrow"|"all">("today");const[selectedDate,setSelectedDate]=useState(localDate());const[busy,setBusy]=useState(false);
  const request=useCallback(async(url:string,options?:RequestInit)=>{const response=await fetch(url,options);const body=await response.json();if(response.status===503&&body.code==="not_configured"){setConnected(false);throw new Error("Supabase не подключён.")}if(!response.ok){const message=body.error||"Ошибка запроса.";setError(message);throw new Error(message)}setConnected(true);setError("");return body},[]);
  const loadServices=useCallback(async()=>{setBusy(true);setError("");try{const body=await request("/api/admin/services");setServices(body.services)}catch(err){setError(err instanceof Error?err.message:"Не удалось загрузить услуги.")}finally{setBusy(false)}},[request]);
  const loadDoctors=useCallback(async()=>{setBusy(true);setError("");try{const body=await request("/api/admin/doctors");setDoctors(body.doctors)}catch(err){setError(err instanceof Error?err.message:"Не удалось загрузить специалистов.")}finally{setBusy(false)}},[request]);
  useEffect(()=>{let active=true;let url="/api/admin/services";if(screen==="appointments"){const date=filter==="all"?undefined:filter==="today"?localDate():localDate(1);url=`/api/admin/appointments${date?`?date=${date}`:""}`}if(screen==="calendar")url=`/api/admin/appointments?date=${selectedDate}`;if(screen==="doctors")url="/api/admin/doctors";fetch(url).then(async response=>({response,body:await response.json()})).then(({response,body})=>{if(!active)return;if(response.status===503&&body.code==="not_configured"){setConnected(false);return}if(!response.ok){setError(body.error||"Не удалось загрузить данные.");return}setConnected(true);setError("");if(screen==="services")setServices(body.services);else if(screen==="doctors")setDoctors(body.doctors);else setAppointments(body.appointments)}).catch(()=>{if(active)setError("Не удалось загрузить данные.")});return()=>{active=false}},[screen,filter,selectedDate]);
  async function updateStatus(id:string,status:AppointmentStatus){try{await request("/api/admin/appointments",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});setAppointments(items=>items.map(item=>item.id===id?{...item,status}:item))}catch(err){setError(err instanceof Error?err.message:"Не удалось обновить запись.")}}
  async function saveService(service:Service){try{await request("/api/admin/services",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:service.id,name:service.name,durationMinutes:service.durationMinutes,active:service.active})});await loadServices()}catch(err){setError(err instanceof Error?err.message:"Не удалось сохранить услугу.")}}
  async function saveDoctor(doctor:Doctor){try{await request("/api/admin/doctors",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:doctor.id,name:doctor.name,specialty:doctor.specialty,active:doctor.active})});await loadDoctors()}catch(err){setError(err instanceof Error?err.message:"Не удалось сохранить специалиста.")}}
  return <main className="min-h-screen bg-background lg:grid lg:grid-cols-[250px_1fr]"><aside className="border-b border-line bg-primary-dark p-5 text-white lg:min-h-screen lg:border-b-0 lg:p-7"><div className="flex items-center justify-between lg:block"><div><p className="font-serif text-2xl">Dream Smile</p><p className="mt-1 text-[9px] font-bold uppercase tracking-[.2em] text-secondary">Админ-панель</p></div><Link href="/" className="rounded-full border border-white/20 px-3 py-2 text-xs font-bold lg:mt-8 lg:inline-block">На сайт</Link></div><nav className="mt-6 flex gap-2 overflow-x-auto pb-1 lg:mt-12 lg:block lg:space-y-2">{tabs.map(([id,label])=><button key={id} onClick={()=>setScreen(id)} className={`min-h-11 shrink-0 rounded-xl px-4 text-left text-sm font-bold lg:w-full ${screen===id?"bg-white text-primary-dark":"text-white/65 hover:bg-white/10"}`}>{label}</button>)}</nav></aside><section className="min-w-0 p-4 sm:p-7 lg:p-10"><div className="mx-auto max-w-[1180px]"><div className="rounded-xl border border-accent/40 bg-[#fbf7ef] p-4 text-sm font-bold text-ink">Демо-режим: авторизация будет подключена перед запуском.</div>{connected===false?<Disconnected/>:<>{error&&<p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>}{screen==="appointments"&&<AppointmentsScreen items={appointments} filter={filter} setFilter={setFilter} updateStatus={updateStatus} busy={busy}/>} {screen==="calendar"&&<CalendarScreen items={appointments} selectedDate={selectedDate} setSelectedDate={setSelectedDate} updateStatus={updateStatus} busy={busy}/>} {screen==="services"&&<ServicesScreen items={services} setItems={setServices} save={saveService} reload={loadServices} request={request} busy={busy}/>} {screen==="doctors"&&<DoctorsScreen items={doctors} setItems={setDoctors} save={saveDoctor} reload={loadDoctors} request={request} busy={busy}/>}</>}</div></section></main>
}

function Disconnected(){return <div className="mt-8 rounded-2xl border border-line bg-white p-8"><h1 className="font-serif text-4xl">Supabase не подключён.</h1><p className="mt-4 text-sm leading-7 text-muted">Добавьте NEXT_PUBLIC_SUPABASE_URL и NEXT_PUBLIC_SUPABASE_ANON_KEY, затем перезапустите приложение.</p></div>}
function Header({title,description}:{title:string;description:string}){return <div className="mt-8"><h1 className="font-serif text-4xl">{title}</h1><p className="mt-2 text-sm text-muted">{description}</p></div>}
function Empty({busy}:{busy:boolean}){return <p className="p-6 text-sm text-muted">{busy?"Загрузка…":"Данных пока нет."}</p>}
function AppointmentsScreen({items,filter,setFilter,updateStatus,busy}:{items:Appointment[];filter:string;setFilter:(value:"today"|"tomorrow"|"all")=>void;updateStatus:(id:string,status:AppointmentStatus)=>void;busy:boolean}){return <><Header title="Записи" description="Заявки пациентов и их текущие статусы"/><div className="mt-6 flex gap-2 overflow-x-auto">{([['today','Сегодня'],['tomorrow','Завтра'],['all','Все']] as const).map(([id,label])=><button key={id} onClick={()=>setFilter(id)} className={`min-h-10 shrink-0 rounded-full px-4 text-xs font-bold ${filter===id?"bg-primary text-white":"border border-line bg-white"}`}>{label}</button>)}</div><AppointmentList items={items} updateStatus={updateStatus} busy={busy}/></>}
function AppointmentList({items,updateStatus,busy}:{items:Appointment[];updateStatus:(id:string,status:AppointmentStatus)=>void;busy:boolean}){return <div className="mt-6 overflow-hidden rounded-2xl border border-line bg-white">{!items.length?<Empty busy={busy}/>:<div className="divide-y divide-line">{items.map(item=><article key={item.id} className="grid gap-4 p-4 md:grid-cols-[64px_1fr_1fr_1fr_auto] md:items-center"><div><b className="text-primary">{item.appointmentTime}</b><p className="text-[10px] text-muted">{item.appointmentDate}</p></div><div><p className="text-sm font-bold">{item.patientName}</p><p className="mt-1 text-xs text-muted">{item.patientPhone}</p></div><div className="text-sm"><p>{item.service?.name||"—"}</p><p className="mt-1 text-xs text-muted">{item.doctor?.name||item.doctor?.specialty||"—"}</p></div><span className="w-fit rounded-full bg-secondary px-3 py-1 text-[11px] font-bold text-primary-dark">{statusLabels[item.status]}</span><div className="flex flex-wrap gap-2 md:max-w-[210px] md:justify-end">{item.status==="new"&&<Action onClick={()=>updateStatus(item.id,"confirmed")}>Подтвердить</Action>}{item.status!=="completed"&&item.status!=="cancelled"&&<Action onClick={()=>updateStatus(item.id,"completed")}>Завершить</Action>}{item.status!=="cancelled"&&<Action onClick={()=>updateStatus(item.id,"cancelled")}>Отменить</Action>}</div></article>)}</div>}</div>}
function Action({children,onClick}:{children:React.ReactNode;onClick:()=>void}){return <button onClick={onClick} className="min-h-9 rounded-lg border border-line px-3 text-[11px] font-bold hover:border-primary">{children}</button>}
function CalendarScreen({items,selectedDate,setSelectedDate,updateStatus,busy}:{items:Appointment[];selectedDate:string;setSelectedDate:(value:string)=>void;updateStatus:(id:string,status:AppointmentStatus)=>void;busy:boolean}){const days=useMemo(()=>Array.from({length:21},(_,index)=>{const date=new Date();date.setHours(0,0,0,0);date.setDate(date.getDate()+index);return date}),[]);return <><Header title="Календарь" description="Выберите день, чтобы посмотреть записи"/><div className="mt-6 grid grid-cols-3 gap-2 sm:grid-cols-5 md:grid-cols-7">{days.map(day=>{const value=`${day.getFullYear()}-${String(day.getMonth()+1).padStart(2,"0")}-${String(day.getDate()).padStart(2,"0")}`;return <button key={value} onClick={()=>setSelectedDate(value)} className={`min-h-[70px] rounded-xl border p-2 ${selectedDate===value?"border-primary bg-primary text-white":"border-line bg-white"}`}><span className="block text-[10px] uppercase">{day.toLocaleDateString("ru-RU",{weekday:"short"})}</span><b className="mt-1 block">{day.getDate()}</b></button>})}</div><AppointmentList items={items} updateStatus={updateStatus} busy={busy}/></>}

function ServicesScreen({items,setItems,save,reload,request,busy}:{items:Service[];setItems:React.Dispatch<React.SetStateAction<Service[]>>;save:(item:Service)=>void;reload:()=>Promise<void>;request:(url:string,options?:RequestInit)=>Promise<unknown>;busy:boolean}){async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);try{await request("/api/admin/services",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:data.get("name"),durationMinutes:Number(data.get("duration"))||null})});form.reset();await reload()}catch{}}return <><Header title="Услуги" description="Названия, длительность и доступность для записи"/><form onSubmit={add} className="mt-6 grid gap-3 rounded-2xl border border-line bg-white p-4 sm:grid-cols-[1fr_180px_auto]"><Input name="name" placeholder="Новая услуга" required/><Input name="duration" type="number" placeholder="Минуты"/><button className="btn-primary !min-h-11">Добавить</button></form><div className="mt-5 space-y-3">{!items.length?<Empty busy={busy}/>:items.map((item,index)=><div key={item.id} className="grid gap-3 rounded-2xl border border-line bg-white p-4 sm:grid-cols-[1fr_150px_auto_auto] sm:items-center"><Input value={item.name} onChange={value=>setItems(current=>current.map((row,i)=>i===index?{...row,name:value}:row))}/><Input type="number" value={item.durationMinutes??""} placeholder="Минуты" onChange={value=>setItems(current=>current.map((row,i)=>i===index?{...row,durationMinutes:Number(value)||null}:row))}/><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={item.active} onChange={event=>setItems(current=>current.map((row,i)=>i===index?{...row,active:event.target.checked}:row))}/> Активна</label><button onClick={()=>save(item)} className="min-h-10 rounded-xl border border-line px-4 text-xs font-bold hover:border-primary">Сохранить</button></div>)}</div></>}
function DoctorsScreen({items,setItems,save,reload,request,busy}:{items:Doctor[];setItems:React.Dispatch<React.SetStateAction<Doctor[]>>;save:(item:Doctor)=>void;reload:()=>Promise<void>;request:(url:string,options?:RequestInit)=>Promise<unknown>;busy:boolean}){async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);try{await request("/api/admin/doctors",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:data.get("name"),specialty:data.get("specialty")})});form.reset();await reload()}catch{}}return <><Header title="Специалисты" description="Профили специалистов и доступность для записи"/><form onSubmit={add} className="mt-6 grid gap-3 rounded-2xl border border-line bg-white p-4 sm:grid-cols-[1fr_1fr_auto]"><Input name="name" placeholder="Имя (необязательно)"/><Input name="specialty" placeholder="Специальность" required/><button className="btn-primary !min-h-11">Добавить</button></form><div className="mt-5 space-y-3">{!items.length?<Empty busy={busy}/>:items.map((item,index)=><div key={item.id} className="grid gap-3 rounded-2xl border border-line bg-white p-4 sm:grid-cols-[1fr_1fr_auto_auto] sm:items-center"><Input value={item.name??""} placeholder="Имя" onChange={value=>setItems(current=>current.map((row,i)=>i===index?{...row,name:value||null}:row))}/><Input value={item.specialty} onChange={value=>setItems(current=>current.map((row,i)=>i===index?{...row,specialty:value}:row))}/><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={item.active} onChange={event=>setItems(current=>current.map((row,i)=>i===index?{...row,active:event.target.checked}:row))}/> Активен</label><button onClick={()=>save(item)} className="min-h-10 rounded-xl border border-line px-4 text-xs font-bold hover:border-primary">Сохранить</button></div>)}</div></>}
function Input({name,type="text",placeholder,value,required,onChange}:{name?:string;type?:string;placeholder?:string;value?:string|number;required?:boolean;onChange?:(value:string)=>void}){return <input name={name} type={type} min={type==="number"?1:undefined} placeholder={placeholder} value={value} required={required} onChange={onChange?event=>onChange(event.target.value):undefined} className="h-11 min-w-0 rounded-xl border border-line px-3 text-sm outline-none focus:border-primary"/>}
