"use client";
import { useEffect, useState } from "react";
import type { Appointment } from "@/types";
import type { AppointmentStatus } from "@/types/database";
import { AdminSidebar } from "@/components/admin/admin-sidebar";

type ArchiveFilter="all"|"completed"|"cancelled";
type ArchiveResponse={appointments:Appointment[];page:number;limit:number;total:number;totalPages:number};
const statusLabels:Record<AppointmentStatus,string>={new:"Новая",confirmed:"Подтверждена",completed:"Завершена",cancelled:"Отменена"};

export function ArchiveScreen(){
  const[filter,setFilter]=useState<ArchiveFilter>("all");const[searchInput,setSearchInput]=useState("");const[search,setSearch]=useState("");const[page,setPage]=useState(1);const[data,setData]=useState<ArchiveResponse>({appointments:[],page:1,limit:50,total:0,totalPages:1});const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[retryKey,setRetryKey]=useState(0);
  useEffect(()=>{const timeout=window.setTimeout(()=>{setSearch(searchInput.trim());setPage(1)},300);return()=>window.clearTimeout(timeout)},[searchInput]);
  useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>{setLoading(true);setError("")});const params=new URLSearchParams({status:filter,search,page:String(page),limit:"50"});fetch(`/api/admin/archive?${params}`,{cache:"no-store",signal:controller.signal}).then(async response=>{const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Не удалось загрузить архив.");setData(body)}).catch(reason=>{if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(reason instanceof Error?reason.message:"Не удалось загрузить архив.")}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[filter,page,retryKey,search]);
  const emptyMessage=search?"По вашему запросу ничего не найдено":"Архив пока пуст";
  return <main className="min-h-screen bg-background lg:grid lg:grid-cols-[250px_1fr]"><AdminSidebar active="archive"/><section className="min-w-0 p-4 sm:p-7 lg:p-10"><div className="mx-auto max-w-[1180px]"><div className="rounded-xl border border-accent/40 bg-[#fbf7ef] p-4 text-sm font-bold text-ink">Защищённая админ-панель Dream Smile</div><header className="mt-8"><h1 className="font-serif text-4xl">Архив записей</h1><p className="mt-2 text-sm text-muted">Завершённые и отменённые записи старше 30 дней</p></header><div className="mt-6 grid gap-3 sm:grid-cols-[minmax(240px,1fr)_auto]"><label><span className="sr-only">Поиск по пациенту или телефону</span><input value={searchInput} onChange={event=>setSearchInput(event.target.value)} placeholder="Поиск по пациенту или телефону" className="h-11 w-full rounded-xl border border-line bg-white px-4 text-sm outline-none focus:border-primary"/></label><div className="flex gap-2 overflow-x-auto">{([['all','Все'],['completed','Завершённые'],['cancelled','Отменённые']] as const).map(([id,label])=><button key={id} type="button" onClick={()=>{setFilter(id);setPage(1)}} className={`min-h-11 shrink-0 rounded-full px-4 text-xs font-bold ${filter===id?"bg-primary text-white":"border border-line bg-white"}`}>{label}</button>)}</div></div>{error?<div role="alert" className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-6 text-sm font-bold text-red-700"><p>{error}</p><button type="button" onClick={()=>setRetryKey(value=>value+1)} className="mt-4 min-h-10 rounded-xl border border-red-200 bg-white px-4 text-xs">Повторить</button></div>:<ArchiveList items={data.appointments} loading={loading} emptyMessage={emptyMessage}/>} {!loading&&!error&&data.total>0&&<div className="mt-5 flex items-center justify-between gap-3 text-sm"><p className="text-muted">{data.total} записей · страница {data.page} из {data.totalPages}</p><div className="flex gap-2"><button type="button" disabled={page<=1} onClick={()=>setPage(value=>Math.max(1,value-1))} className="min-h-10 rounded-xl border border-line bg-white px-4 text-xs font-bold disabled:opacity-40">Назад</button><button type="button" disabled={page>=data.totalPages} onClick={()=>setPage(value=>value+1)} className="min-h-10 rounded-xl border border-line bg-white px-4 text-xs font-bold disabled:opacity-40">Вперёд</button></div></div>}</div></section></main>
}

function ArchiveList({items,loading,emptyMessage}:{items:Appointment[];loading:boolean;emptyMessage:string}){return <div className="mt-6 min-w-0 overflow-hidden rounded-2xl border border-line bg-white">{loading?<ArchiveSkeleton/>:!items.length?<p className="p-8 text-center text-sm text-muted">{emptyMessage}</p>:<><div className="hidden grid-cols-[105px_minmax(120px,1.2fr)_130px_minmax(120px,1.2fr)_minmax(110px,1fr)_112px] gap-3 border-b border-line bg-background/70 px-4 py-3 text-[9px] font-extrabold uppercase tracking-[.06em] text-muted xl:grid"><span>Дата и время</span><span>Пациент</span><span>Телефон</span><span>Услуга</span><span>Специалист</span><span>Статус</span></div><div className="divide-y divide-line">{items.map(item=><article key={item.id} className="grid min-w-0 gap-4 p-4 xl:min-h-[82px] xl:grid-cols-[105px_minmax(120px,1.2fr)_130px_minmax(120px,1.2fr)_minmax(110px,1fr)_112px] xl:items-center"><ArchiveCell label="Дата и время"><b className="text-sm text-primary">{item.appointmentTime}</b><p className="mt-1 text-[10px] text-muted">{item.appointmentDate}</p></ArchiveCell><ArchiveCell label="Пациент"><p className="break-words text-sm font-bold">{item.patientName}</p></ArchiveCell><ArchiveCell label="Телефон"><a href={`tel:${item.patientPhone}`} className="break-all text-xs text-muted hover:text-primary">{item.patientPhone}</a></ArchiveCell><ArchiveCell label="Услуга"><p className="break-words text-sm">{item.service?.name||"—"}</p></ArchiveCell><ArchiveCell label="Специалист"><p className="break-words text-sm font-bold">{item.doctor?.name||item.doctor?.specialty||"—"}</p></ArchiveCell><ArchiveCell label="Статус"><span className={`inline-flex min-h-7 items-center rounded-full px-3 text-[11px] font-bold ${item.status==="completed"?"bg-[#e8efec] text-[#52655d]":"bg-[#f4eeee] text-[#806566]"}`}>{statusLabels[item.status]}</span></ArchiveCell></article>)}</div></>}</div>}
function ArchiveCell({label,children}:{label:string;children:React.ReactNode}){return <div className="min-w-0"><p className="mb-1.5 text-[10px] font-extrabold uppercase tracking-[.08em] text-muted xl:hidden">{label}</p>{children}</div>}
function ArchiveSkeleton(){return <div aria-label="Загрузка архива" className="divide-y divide-line">{[0,1,2,3].map(row=><div key={row} className="grid animate-pulse gap-3 p-4 xl:grid-cols-6">{[0,1,2,3,4,5].map(cell=><span key={cell} className="h-8 rounded-lg bg-background"/>)}</div>)}</div>}
