"use client";

import { FormEvent, useEffect, useState } from "react";
import type { Doctor } from "@/types";

export type DoctorAccountAction="create"|"password"|"disconnect";

export function DoctorAccountModal({doctor,action,onClose,onSuccess}:{doctor:Doctor;action:DoctorAccountAction;onClose:()=>void;onSuccess:(message:string,account?:Doctor["account"])=>void}){
  const[loading,setLoading]=useState(false);const[error,setError]=useState("");
  useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow="hidden";const close=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!loading)onClose()};window.addEventListener("keydown",close);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",close)}},[loading,onClose]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget);const email=String(form.get("email")||"").trim().toLowerCase();const password=String(form.get("password")||"");const confirmation=String(form.get("confirmation")||"");if(action==="create"&&!/^\S+@\S+\.\S+$/.test(email)){setError("Введите корректный email.");return}if(action!=="disconnect"&&password.length<8){setError("Пароль должен содержать минимум 8 символов.");return}if(action!=="disconnect"&&password!==confirmation){setError("Пароли не совпадают.");return}setLoading(true);try{const base=`/api/admin/doctors/${doctor.id}/account`;const url=action==="password"?`${base}/password`:base;const method=action==="create"?"POST":action==="password"?"PATCH":"DELETE";const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:action==="disconnect"?undefined:JSON.stringify(action==="create"?{email,password}:{password})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Не удалось выполнить действие.");onSuccess(body.message||successMessage(action),action==="create"?body.account:action==="disconnect"?null:undefined)}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось выполнить действие.")}finally{setLoading(false)}}
  const title=action==="create"?"Создать аккаунт врача":action==="password"?"Сменить пароль":"Отключить аккаунт";
  return <div className="fixed inset-0 z-[120] grid place-items-center overflow-y-auto bg-primary-dark/35 p-3 backdrop-blur-[2px] sm:p-6" onMouseDown={event=>{if(event.target===event.currentTarget&&!loading)onClose()}}><section role="dialog" aria-modal="true" aria-labelledby="doctor-account-modal-title" className="motion-page-enter my-auto w-full max-w-lg rounded-[26px] border border-white/80 bg-white p-5 shadow-[0_28px_80px_rgba(15,78,85,.2)] sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">{doctor.name||doctor.specialty}</p><h2 id="doctor-account-modal-title" className="mt-2 font-serif text-3xl">{title}</h2></div><button type="button" disabled={loading} aria-label="Закрыть" onClick={onClose} className="focus-ring grid h-10 w-10 shrink-0 place-items-center rounded-full border border-line text-xl text-muted hover:border-primary">×</button></div><form onSubmit={submit} className="mt-6 space-y-4">{action==="create"&&<AccountField label="Email *"><input name="email" type="email" inputMode="email" autoComplete="off" required disabled={loading} className="time-input" placeholder="doctor@example.com"/></AccountField>}{action!=="disconnect"&&<><AccountField label={action==="create"?"Пароль *":"Новый пароль *"}><input name="password" type="password" autoComplete="new-password" required minLength={8} disabled={loading} className="time-input"/></AccountField><AccountField label="Повторите пароль *"><input name="confirmation" type="password" autoComplete="new-password" required minLength={8} disabled={loading} className="time-input"/></AccountField></>}{action==="disconnect"&&<div className="rounded-xl border border-[#eadede] bg-[#fbf7f7] p-4 text-sm leading-6 text-[#684f50]"><p className="font-bold">Вы уверены, что хотите отключить аккаунт врача?</p><p className="mt-1">Врач больше не сможет войти в кабинет. Профиль врача, записи и расписание останутся без изменений.</p></div>}{error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<div className="flex flex-col-reverse gap-3 pt-2 sm:flex-row sm:justify-end"><button type="button" disabled={loading} onClick={onClose} className="btn-secondary focus-ring !min-h-11">Отмена</button><button type="submit" disabled={loading} className={`${action==="disconnect"?"border border-[#d8bcbc] bg-[#806566]":"btn-primary"} focus-ring inline-flex min-h-11 items-center justify-center rounded-full px-6 text-sm font-bold text-white disabled:cursor-wait disabled:opacity-60`}>{loading?"Сохраняем…":action==="create"?"Создать аккаунт":action==="password"?"Сменить пароль":"Отключить"}</button></div></form></section></div>;
}

function AccountField({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-bold">{label}</span>{children}</label>}
function successMessage(action:DoctorAccountAction){return action==="create"?"Аккаунт врача создан":action==="password"?"Пароль врача изменён":"Аккаунт врача отключён"}
