"use client";

import { useCallback, useEffect, useState } from "react";
import type { Appointment, Doctor } from "@/types";
import type { AppointmentStatus } from "@/types/database";
import { DoctorSidebar } from "./doctor-sidebar";
import { createWhatsAppUrl } from "@/lib/whatsapp";

type Filter="today"|"tomorrow"|"upcoming";
const labels:Record<AppointmentStatus,string>={new:"Новая",confirmed:"Подтверждена",completed:"Завершена",cancelled:"Отменена"};

export function DoctorDashboard({doctor}:{doctor:Pick<Doctor,"id"|"name"|"specialty"|"phone">}){
  const[filter,setFilter]=useState<Filter>("today");const[items,setItems]=useState<Appointment[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[updatingId,setUpdatingId]=useState<string|null>(null);const[error,setError]=useState("");
  const load=useCallback(async(manual=false)=>{if(manual)setRefreshing(true);else setLoading(true);setError("");try{const response=await fetch(`/api/doctor/appointments?filter=${filter}`,{cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Не удалось загрузить записи.");setItems(body.appointments)}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось загрузить записи.")}finally{setLoading(false);setRefreshing(false)}},[filter]);
  useEffect(()=>{queueMicrotask(()=>{void load()})},[load]);
  async function complete(id:string){setUpdatingId(id);setError("");try{const response=await fetch("/api/doctor/appointments",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:"completed"})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Не удалось завершить запись.");setItems(current=>current.map(item=>item.id===id?{...item,status:"completed"}:item))}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось завершить запись.")}finally{setUpdatingId(null)}}
  return <main className="min-h-screen bg-background lg:grid lg:grid-cols-[240px_1fr]"><DoctorSidebar active="appointments"/><section className="min-w-0 p-4 sm:p-7 lg:p-10"><div className="mx-auto max-w-5xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Кабинет врача</p><h1 className="mt-3 font-serif text-4xl">Здравствуйте, {doctor.name||doctor.specialty}</h1><p className="mt-2 text-sm text-muted">Здесь отображаются только ваши записи.</p></div><button type="button" disabled={refreshing} onClick={()=>{void load(true)}} className="focus-ring min-h-11 rounded-full border border-line bg-white px-5 text-xs font-bold hover:border-primary disabled:opacity-60">{refreshing?"Обновляем…":"↻ Обновить"}</button></header><div className="mt-7 flex gap-2 overflow-x-auto pb-1">{([['today','Сегодня'],['tomorrow','Завтра'],['upcoming','Предстоящие']] as const).map(([id,label])=><button key={id} type="button" onClick={()=>setFilter(id)} className={`min-h-10 shrink-0 rounded-full px-4 text-xs font-bold ${filter===id?"bg-primary text-white":"border border-line bg-white"}`}>{label}</button>)}</div>{error&&<p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>}<DoctorAppointments items={items} loading={loading} updatingId={updatingId} complete={complete}/></div></section></main>;
}

function DoctorAppointments({items,loading,updatingId,complete}:{items:Appointment[];loading:boolean;updatingId:string|null;complete:(id:string)=>Promise<void>}){if(loading)return <div className="mt-6 space-y-3">{[0,1,2].map(item=><div key={item} className="h-36 animate-pulse rounded-2xl border border-line bg-white"/>)}</div>;if(!items.length)return <p className="mt-6 rounded-2xl border border-line bg-white p-8 text-center text-sm text-muted">Записей нет.</p>;return <div className="mt-6 space-y-3">{items.map(item=><DoctorAppointmentCard key={item.id} item={item} updating={updatingId===item.id} complete={complete}/>)}</div>}
function DoctorAppointmentCard({item,updating,complete}:{item:Appointment;updating:boolean;complete:(id:string)=>Promise<void>}){const[contactError,setContactError]=useState("");function whatsapp(){const url=createWhatsAppUrl(item);if(!url){setContactError("Некорректный номер пациента.");return}setContactError("");window.open(url,"_blank","noopener,noreferrer")}const color=item.status==="new"?"border-[#cfe7d5] bg-[#fbfefc]":"border-line bg-white";return <article className={`motion-card rounded-2xl border p-4 sm:p-5 ${color}`}><div className="grid gap-4 md:grid-cols-[110px_1.2fr_1fr_120px] md:items-start"><div><p className="text-2xl font-bold text-primary">{item.appointmentTime}</p><p className="mt-1 text-xs text-muted">{new Date(`${item.appointmentDate}T12:00:00Z`).toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"})}</p></div><div><p className="text-sm font-bold">{item.patientName}</p><a href={`tel:${item.patientPhone}`} className="mt-1 inline-block text-xs text-primary hover:underline">{item.patientPhone}</a><p className="mt-3 text-xs text-muted">{item.service?.name||"—"}</p></div><div><p className="text-[10px] font-extrabold uppercase tracking-[.08em] text-muted">Комментарий</p><p className="mt-1 break-words text-sm leading-5">{item.comment||"Нет комментария"}</p></div><span className={`inline-flex min-h-7 w-fit items-center rounded-full px-3 text-[11px] font-bold ${item.status==="new"?"bg-[#edf6ef] text-[#426a4b]":item.status==="confirmed"?"bg-secondary text-primary-dark":"bg-[#edf0ef] text-[#60706a]"}`}>{labels[item.status]}</span></div><div className="mt-4 flex flex-wrap gap-2 border-t border-line pt-4"><a href={`tel:${item.patientPhone}`} className="inline-flex min-h-10 items-center rounded-xl border border-line px-4 text-xs font-bold hover:border-primary">Позвонить</a><button type="button" onClick={whatsapp} className="focus-ring min-h-10 rounded-xl border border-[#cfe7d5] bg-[#f1f8f3] px-4 text-xs font-bold text-[#39734a] hover:border-[#7db98c]">WhatsApp</button>{item.status==="confirmed"&&<button type="button" disabled={updating} onClick={()=>{void complete(item.id)}} className="focus-ring min-h-10 rounded-xl bg-primary px-4 text-xs font-bold text-white disabled:opacity-60">{updating?"Сохраняем…":"Завершить"}</button>}{contactError&&<p role="alert" className="w-full text-xs font-bold text-red-700">{contactError}</p>}</div></article>}
