"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import { LoadingSpinner } from "@/components/loading-spinner";
import { createSupabaseAuthBrowserClient } from "@/lib/supabase/auth-browser";

function message(value:string){const text=value.toLowerCase();if(text.includes("invalid login credentials"))return"Неверный email или пароль.";if(text.includes("email not confirmed"))return"Email ещё не подтверждён.";if(text.includes("rate limit")||text.includes("too many"))return"Слишком много попыток. Попробуйте позже.";return"Не удалось войти. Попробуйте ещё раз."}

export function DoctorLoginForm(){
  const router=useRouter();const[loading,setLoading]=useState(false);const[error,setError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(loading)return;setError("");const form=new FormData(event.currentTarget);const email=String(form.get("email")||"").trim().toLowerCase();const password=String(form.get("password")||"");if(!/^\S+@\S+\.\S+$/.test(email)){setError("Введите корректный email.");return}if(password.length<6){setError("Пароль должен содержать не менее 6 символов.");return}const supabase=createSupabaseAuthBrowserClient();if(!supabase){setError("Supabase не подключён.");return}setLoading(true);try{const{error:signInError}=await supabase.auth.signInWithPassword({email,password});if(signInError){setError(message(signInError.message));return}router.replace("/doctor")}catch{setError("Не удалось связаться с сервером. Попробуйте ещё раз.")}finally{setLoading(false)}}
  return <form onSubmit={submit} noValidate aria-busy={loading} className="space-y-5"><label className="block"><span className="mb-2 block text-xs font-bold">Email</span><input name="email" type="email" inputMode="email" autoComplete="email" disabled={loading} required className="focus-ring h-12 w-full rounded-xl border border-line px-4 text-sm outline-none focus:border-primary"/></label><label className="block"><span className="mb-2 block text-xs font-bold">Пароль</span><input name="password" type="password" autoComplete="current-password" disabled={loading} required minLength={6} className="focus-ring h-12 w-full rounded-xl border border-line px-4 text-sm outline-none focus:border-primary"/></label>{error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<button type="submit" disabled={loading} aria-busy={loading} className="btn-primary focus-ring w-full disabled:cursor-wait disabled:opacity-60">{loading&&<LoadingSpinner/>}{loading?"Входим…":"Войти"}</button></form>
}
